package com.neshtek.expertconnect.service;

import com.neshtek.expertconnect.entity.Invoice;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class InvoicePdfService {
    public byte[] generate(Invoice invoice) {
        try (PDDocument document = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font normal = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            try (PDPageContentStream stream = new PDPageContentStream(document, page)) {
                float y = 770;
                stream.beginText(); stream.setFont(bold, 22); stream.newLineAtOffset(50, y); stream.showText("NeshTek Expert Connect"); stream.endText();
                y -= 35; line(stream, bold, "INVOICE", 50, y, 16); line(stream, bold, invoice.getInvoiceNumber(), 390, y, 13);
                y -= 35; line(stream, normal, "Invoice date: " + invoice.getInvoiceDate(), 50, y, 10); line(stream, normal, "Due date: " + (invoice.getDueDate()==null?"-":invoice.getDueDate()), 300, y, 10);
                y -= 28; line(stream, bold, "Customer", 50, y, 11); y -= 18; line(stream, normal, safe(invoice.getCustomer()==null?null:invoice.getCustomer().getCompanyName()), 50, y, 10);
                y -= 28; line(stream, bold, "Engagement", 50, y, 11); y -= 18; line(stream, normal, "Engagement #" + (invoice.getEngagement()==null?"-":invoice.getEngagement().getId()), 50, y, 10);
                y -= 35; line(stream, bold, "Description", 50, y, 10); line(stream, bold, "Amount", 430, y, 10);
                y -= 20; line(stream, normal, "Approved work billing", 50, y, 10); line(stream, normal, money(invoice.getSubtotalAmount(), invoice.getCurrencyCode()), 430, y, 10);
                y -= 20; line(stream, normal, "Tax", 50, y, 10); line(stream, normal, money(invoice.getTaxAmount(), invoice.getCurrencyCode()), 430, y, 10);
                y -= 25; line(stream, bold, "Total", 50, y, 12); line(stream, bold, money(invoice.getTotalAmount(), invoice.getCurrencyCode()), 430, y, 12);
                y -= 25; line(stream, normal, "Paid", 50, y, 10); line(stream, normal, money(invoice.getPaidAmount(), invoice.getCurrencyCode()), 430, y, 10);
                y -= 25; line(stream, bold, "Balance due", 50, y, 11); line(stream, bold, money(invoice.getTotalAmount().subtract(invoice.getPaidAmount()), invoice.getCurrencyCode()), 430, y, 11);
                y -= 45; line(stream, normal, "Status: " + invoice.getStatus(), 50, y, 10);
                if (invoice.getNotes()!=null) { y -= 28; line(stream, normal, "Notes: " + trim(invoice.getNotes(), 110), 50, y, 9); }
                y -= 55; line(stream, normal, "Generated by NeshTek Expert Connect", 50, y, 8);
            }
            document.save(out);
            return out.toByteArray();
        } catch (Exception e) {
            throw new IllegalStateException("Unable to generate invoice PDF", e);
        }
    }
    private void line(PDPageContentStream s, PDType1Font f, String text, float x, float y, float size) throws Exception { s.beginText(); s.setFont(f,size); s.newLineAtOffset(x,y); s.showText(safe(text)); s.endText(); }
    private String safe(String s){return s==null?"-":s.replaceAll("[^\\x20-\\x7E]", " ");}
    private String money(java.math.BigDecimal amount,String currency){return (currency==null?"":currency+" ")+(amount==null?"0.00":amount.setScale(2,java.math.RoundingMode.HALF_UP));}
    private String trim(String s,int max){return s.length()<=max?s:s.substring(0,max-3)+"...";}
}
