import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth/auth.service';

interface Requirement { id:number; customerId:number|null; companyName:string; contactName:string; email:string; title:string; description:string; technology:string; requiredExperienceYears:number; estimatedHours:number; preferredStartDate:string; priority:string; budget:number; currencyCode:string; status:string; createdAt:string; updatedAt:string; skills:{id:number;skillName:string;priorityOrder:number;mandatory:boolean}[]; }
interface Page<T> { content:T[]; totalElements:number; totalPages:number; }

@Component({
 selector:'app-admin-requirements', standalone:true, imports:[CommonModule,FormsModule],
 template:`
 <main class="page"><header class="topbar"><div><div class="brand">NeshTek Expert Connect</div><div class="subtitle">Administration / Requirements</div></div><div class="actions"><button (click)="back()">Dashboard</button><button (click)="logout()">Sign out</button></div></header>
 <section class="hero"><div><div class="eyebrow">Requirement administration</div><h1>Requirement management</h1><p>Review customer requirements, priorities and requested expertise.</p></div><button class="refresh" (click)="load()" [disabled]="loading">{{loading?'Refreshing…':'Refresh'}}</button></section>
 <section *ngIf="error" class="error">{{error}}</section>
 <section class="panel"><div class="toolbar"><strong>{{total}} requirement{{total===1?'':'s'}}</strong><div class="filters"><input [(ngModel)]="search" placeholder="Search title, company or technology" (keyup.enter)="applySearch()"><button class="search" (click)="applySearch()">Search</button><select [(ngModel)]="status" (change)="applySearch()"><option value="ALL">All statuses</option><option value="SUBMITTED">Submitted</option><option value="OPEN">Open</option><option value="MATCHED">Matched</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></div></div>
 <div class="table-wrap"><table><thead><tr><th>Requirement</th><th>Customer</th><th>Technology</th><th>Experience</th><th>Hours</th><th>Priority</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody><tr *ngFor="let r of filtered"><td><b>{{r.title}}</b></td><td>{{r.companyName || r.contactName || r.email}}</td><td>{{r.technology || '—'}}</td><td>{{r.requiredExperienceYears || 0}} yrs</td><td>{{r.estimatedHours || 0}}</td><td><span class="priority" [class.high]="r.priority==='HIGH'||r.priority==='URGENT'">{{r.priority}}</span></td><td><span class="status">{{r.status}}</span></td><td>{{r.createdAt|date:'mediumDate'}}</td><td><button class="link" (click)="view(r)">View</button></td></tr><tr *ngIf="!loading && filtered.length===0"><td colspan="9" class="empty">No requirements found.</td></tr></tbody></table></div>
 <div class="pager"><button (click)="previous()" [disabled]="page===0||loading">Previous</button><span>Page {{page+1}} of {{totalPages||1}}</span><button (click)="next()" [disabled]="page+1>=totalPages||loading">Next</button></div></section>
 <section *ngIf="selected" class="panel detail"><div class="detail-head"><div><div class="eyebrow">Requirement details</div><h2>{{selected.title}}</h2><p>{{selected.companyName}} · {{selected.contactName}} · {{selected.email}}</p></div><button class="close" (click)="selected=null">Close</button></div><p class="description">{{selected.description}}</p><div class="detail-grid"><div><b>Technology</b><span>{{selected.technology||'—'}}</span></div><div><b>Experience</b><span>{{selected.requiredExperienceYears||0}} years</span></div><div><b>Estimated hours</b><span>{{selected.estimatedHours||0}}</span></div><div><b>Start date</b><span>{{selected.preferredStartDate||'—'}}</span></div><div><b>Priority</b><span>{{selected.priority}}</span></div><div><b>Budget</b><span>{{selected.budget||0}} {{selected.currencyCode}}</span></div><div><b>Status</b><span>{{selected.status}}</span></div><div><b>Customer ID</b><span>{{selected.customerId||'—'}}</span></div></div><div class="skills"><h3>Required skills</h3><span *ngFor="let s of selected.skills" class="skill">{{s.skillName}}{{s.mandatory?' · Mandatory':''}}</span><span *ngIf="!selected.skills?.length" class="muted">No skills listed.</span></div></section></main>`,
 styles:[`.page{min-height:100vh;background:#f7f9fc;color:#172033;font-family:Inter,system-ui,sans-serif;padding:0 32px 48px}.topbar,.hero,.panel,.error{max-width:1200px;margin:auto}.topbar{padding:22px 0;border-bottom:1px solid #e3e8f0;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:850}.subtitle,td{color:#667085;font-size:14px}.subtitle{margin-top:4px}.actions,.filters{display:flex;gap:8px}.topbar button,.refresh,.search,.link,.close,.pager button,.filters input,.filters select{border:1px solid #d5dbe6;background:#fff;border-radius:9px;padding:10px 13px;font-weight:700;cursor:pointer}.hero{padding:46px 0 24px;display:flex;justify-content:space-between;align-items:end;gap:20px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:850;color:#315ea8}.hero h1{font-size:40px;margin:9px 0}.hero p{color:#667085}.error{margin-bottom:18px;padding:12px 14px;border:1px solid #e8b4b4;background:#fff5f5;border-radius:10px;color:#a33}.panel{background:#fff;border:1px solid #e1e6ef;border-radius:16px;box-shadow:0 12px 32px rgba(23,32,51,.05);overflow:hidden}.toolbar{padding:18px 20px;border-bottom:1px solid #e5e9f0;display:flex;justify-content:space-between;gap:15px;align-items:center}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1250px}th,td{text-align:left;padding:15px 16px;border-bottom:1px solid #eef1f5}th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#667085;background:#fbfcfe}.status,.priority{display:inline-block;padding:5px 9px;border-radius:999px;background:#f1f3f6;font-size:11px;font-weight:850}.priority.high{background:#fff0e8;color:#a64b00}.link{background:transparent;border-color:transparent;color:#315ea8}.empty{text-align:center;padding:36px}.pager{display:flex;justify-content:center;align-items:center;gap:18px;padding:16px}.detail{margin-top:24px;padding:24px}.detail-head{display:flex;justify-content:space-between;align-items:start}.detail h2{margin:8px 0}.detail p{color:#667085}.description{padding:15px;background:#f8fafc;border-radius:10px;line-height:1.6}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:20px}.detail-grid div{border:1px solid #e5e9f0;border-radius:10px;padding:14px}.detail-grid b,.detail-grid span{display:block}.detail-grid span{margin-top:6px;color:#667085}.skills{margin-top:22px}.skill{display:inline-block;padding:7px 10px;margin:4px;border-radius:999px;background:#eef4ff;color:#315ea8;font-size:12px;font-weight:700}.muted{color:#667085}@media(max-width:900px){.page{padding:0 18px 36px}.hero,.toolbar{align-items:start;flex-direction:column}.filters{width:100%;flex-wrap:wrap}.detail-grid{grid-template-columns:repeat(2,1fr)}}`]
})
export class AdminRequirementsComponent {
 private readonly http=inject(HttpClient); private readonly auth=inject(AuthService); private readonly router=inject(Router); private readonly base='http://localhost:8080/api/v1/admin/requirements';
 requirements:Requirement[]=[]; filtered:Requirement[]=[]; selected:Requirement|null=null; page=0; size=20; total=0; totalPages=0; search=''; status='ALL'; loading=false; error='';
 constructor(){const u=this.auth.getCurrentUser();if(!u||!['ADMIN','ROLE_ADMIN'].includes(u.role)){this.router.navigateByUrl('/');return;}this.load();}
 load(){this.loading=true;this.error='';this.http.get<Page<Requirement>>(`${this.base}?page=${this.page}&size=${this.size}`).subscribe({next:p=>{this.requirements=p.content;this.total=p.totalElements;this.totalPages=p.totalPages;this.filter();this.loading=false;},error:e=>{console.error(e);this.error=e?.error?.message||'Unable to load requirements.';this.loading=false;}})}
 filter(){const q=this.search.trim().toLowerCase();this.filtered=this.requirements.filter(r=>(this.status==='ALL'||r.status===this.status)&&(!q||`${r.title} ${r.companyName} ${r.contactName} ${r.email} ${r.technology}`.toLowerCase().includes(q)));}
 applySearch(){this.page=0;this.filter();}
 view(r:Requirement){this.http.get<Requirement>(`${this.base}/${r.id}`).subscribe({next:x=>this.selected=x,error:e=>{console.error(e);this.error=e?.error?.message||'Unable to load requirement details.';}})}
 next(){if(this.page+1<this.totalPages){this.page++;this.load()}} previous(){if(this.page>0){this.page--;this.load()}} back(){this.router.navigateByUrl('/admin/dashboard')} logout(){this.auth.logout();this.router.navigateByUrl('/login')}
}
