import { Component, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth/auth.service';
import { ExpertReplacement, ExpertMatch, ExpertReplacementService } from '../core/replacement/expert-replacement.service';

@Component({
  selector:'app-admin-expert-replacements', standalone:true, imports:[CommonModule,DatePipe],
  template:`
  <main class="page"><header class="topbar"><div><div class="brand">NeshTek Expert Connect</div><div class="subtitle">Administration · Expert Replacement</div></div><div class="top-actions"><button type="button" (click)="back()">Dashboard</button><button type="button" (click)="logout()">Sign out</button></div></header>
  <section class="hero"><div class="eyebrow">Replacement operations</div><h1>Expert Replacement Requests</h1><p>Review customer requests, inspect financial impact, compare replacement experts and create a new engagement without changing historical work.</p></section>
  @if(error){<div class="error">{{error}}</div>}
  @if(loading){<div class="state">Loading replacement requests…</div>}@else if(!items.length){<div class="panel state">No pending replacement requests.</div>}@else{
    <section class="grid">@for(r of items;track r.id){<article class="panel"><div class="row"><div><div class="eyebrow">Request #{{r.id}}</div><h2>{{r.requirementTitle}}</h2><p>Engagement #{{r.engagementId}} · Current expert <b>{{r.expertName}}</b></p></div><span class="status">{{r.status}}</span></div>
      <div class="details"><div><span>Reason</span><b>{{r.reasonCode}}</b></div><div><span>Approved hours</span><b>{{r.approvedHours}}</b></div><div><span>Eligible</span><b>{{r.currencyCode}} {{r.eligibleAmount}}</b></div><div><span>Paid</span><b>{{r.currencyCode}} {{r.paidAmount}}</b></div><div><span>Balance due</span><b>{{r.currencyCode}} {{r.balanceDue}}</b></div><div><span>Refund / credit</span><b>{{r.currencyCode}} {{r.refundOrCreditDue}}</b></div></div>
      <div class="comment"><span>Customer comments</span><p>{{r.comments}}</p></div>
      <div class="actions"><button *ngIf="r.status==='REQUESTED'" (click)="approve(r)">Approve</button><button class="danger" *ngIf="r.status==='REQUESTED'" (click)="reject(r)">Reject</button><button *ngIf="r.status==='APPROVED'" (click)="loadMatches(r)">{{selectedId===r.id?'Refresh matches':'Find replacement experts'}}</button></div>
      @if(selectedId===r.id){<div class="matches"><div class="match-head"><h3>Recommended replacement experts</h3><span>{{matches.length}} found</span></div>@if(matchLoading){<div class="state small">Finding experts…</div>}@else if(!matches.length){<div class="state small">No active matching experts found.</div>}@else{@for(m of matches;track m.expertId){<div class="match"><div><b>{{m.firstName}} {{m.lastName}}</b><small>{{m.city||'—'}} · {{m.totalExperienceYears}} years · {{m.hourlyRate||'—'}} {{m.currencyCode||''}}</small><small>{{m.matchLevel}} · {{m.matchScore}}% · {{m.recommendation}}</small></div><button (click)="assign(r,m)" [disabled]="assigning">Assign</button></div>}}</div>}
    </article>}</section>}
  </main>`,
  styles:[`.page{min-height:100vh;background:#f7f9fc;color:#172033;font-family:Inter,system-ui,sans-serif;padding:0 32px 50px}.topbar{max-width:1240px;margin:auto;padding:22px 0;border-bottom:1px solid #e3e8f0;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:850}.subtitle,small{color:#667085;font-size:13px}.subtitle{margin-top:4px}.top-actions{display:flex;gap:8px}.topbar button,.actions button,.match button{border:1px solid #d5dbe6;background:#fff;color:#172033;border-radius:9px;padding:10px 14px;font-weight:750;cursor:pointer}.hero{max-width:1240px;margin:0 auto;padding:48px 0 24px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:850;color:#315ea8}.hero h1{font-size:40px;margin:8px 0}.hero p{color:#667085;max-width:850px;line-height:1.55}.error{max-width:1240px;margin:0 auto 18px;padding:12px 14px;border:1px solid #e8b4b4;background:#fff5f5;border-radius:10px;color:#a33}.grid{max-width:1240px;margin:auto;display:grid;gap:18px}.panel{background:#fff;border:1px solid #e1e6ef;border-radius:15px;box-shadow:0 12px 32px rgba(23,32,51,.05);padding:22px}.row{display:flex;justify-content:space-between;gap:20px}.row h2{margin:8px 0}.row p{margin:0;color:#667085;font-size:13px}.status{background:#fff4d6;color:#8a5a00;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:850;height:max-content}.details{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:22px 0}.details div{background:#f7f9fc;border-radius:10px;padding:12px}.details span,.comment>span{display:block;color:#667085;font-size:11px;text-transform:uppercase;font-weight:800}.details b{display:block;margin-top:6px}.comment{border-top:1px solid #edf0f5;padding-top:15px}.comment p{font-size:13px;line-height:1.5}.actions{display:flex;gap:8px;margin-top:18px}.danger{color:#b42318!important}.matches{margin-top:20px;border-top:1px solid #edf0f5;padding-top:18px}.match-head{display:flex;justify-content:space-between;align-items:center}.match-head h3{margin:0}.match-head span{font-size:12px;color:#667085}.match{display:flex;justify-content:space-between;align-items:center;gap:20px;border:1px solid #e5e9f0;border-radius:12px;padding:14px;margin-top:10px}.match small{display:block;margin-top:5px;line-height:1.35}.state{text-align:center;padding:48px;color:#667085}.state.small{padding:25px}@media(max-width:850px){.page{padding:0 18px 40px}.details{grid-template-columns:1fr 1fr 1fr}.row{flex-direction:column}}@media(max-width:520px){.details{grid-template-columns:1fr 1fr}.topbar{align-items:start;gap:12px;flex-direction:column}.hero h1{font-size:32px}}`]
})
export class AdminExpertReplacementsComponent {
  private readonly auth=inject(AuthService); private readonly service=inject(ExpertReplacementService); private readonly router=inject(Router);
  items:ExpertReplacement[]=[]; matches:ExpertMatch[]=[]; loading=false; matchLoading=false; assigning=false; selectedId:number|null=null; error='';
  constructor(){const user=this.auth.getCurrentUser();if(!user||!['ADMIN','ROLE_ADMIN'].includes(user.role)){this.router.navigateByUrl('/');return;}this.load();}
  load(){this.loading=true;this.error='';this.service.pending().subscribe({next:r=>{this.items=r??[];this.loading=false;},error:e=>{this.error=this.message(e,'Unable to load replacement requests.');this.loading=false;}});}
  approve(r:ExpertReplacement){const comment=window.prompt('Optional approval comment:')??'';this.service.approve(r.id,comment).subscribe({next:()=>this.load(),error:e=>this.error=this.message(e,'Unable to approve request.')});}
  reject(r:ExpertReplacement){const reason=window.prompt('Rejection reason (required):');if(!reason?.trim())return;this.service.reject(r.id,reason.trim()).subscribe({next:()=>this.load(),error:e=>this.error=this.message(e,'Unable to reject request.')});}
  loadMatches(r:ExpertReplacement){this.selectedId=r.id;this.matches=[];this.matchLoading=true;this.service.matches(r.id,10).subscribe({next:m=>{this.matches=m??[];this.matchLoading=false;},error:e=>{this.error=this.message(e,'Unable to find replacement experts.');this.matchLoading=false;}});}
  assign(r:ExpertReplacement,m:ExpertMatch){if(!window.confirm(`Assign ${m.firstName} ${m.lastName} as replacement expert? This will close the old engagement and create a new engagement for the remaining hours.`))return;this.assigning=true;this.service.assign(r.id,m.expertId).subscribe({next:()=>{this.assigning=false;this.selectedId=null;this.matches=[];this.load();},error:e=>{this.assigning=false;this.error=this.message(e,'Unable to assign replacement expert.');}});}
  message(e:any,fallback:string){return e?.error?.message||e?.error?.error||fallback;} back(){this.router.navigateByUrl('/admin/dashboard');} logout(){this.auth.logout();this.router.navigateByUrl('/login');}
}
