import { Component, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../core/auth/auth.service';
import { ExpertReplacement, ExpertReplacementService } from '../core/replacement/expert-replacement.service';

@Component({selector:'app-customer-expert-replacement',standalone:true,imports:[CommonModule,DatePipe],template:`
<main class="page"><header class="topbar"><div><div class="brand">NeshTek Expert Connect</div><div class="subtitle">Customer · Expert replacement</div></div><div class="top-actions"><button (click)="back()">Dashboard</button><button (click)="logout()">Sign out</button></div></header>
<section class="hero"><div class="eyebrow">Engagement #{{engagementId}}</div><h1>Request an expert replacement</h1><p>Your existing work and payments are preserved. While the request is being reviewed, new or changed work logs are frozen.</p></section>
@if(error){<div class="error">{{error}}</div>}
<section class="panel"><h2>Replacement reason</h2><div class="form"><label>Reason<select [(ngModel)]="reason"><option value="SKILLS_MISMATCH">Skills mismatch</option><option value="QUALITY_ISSUE">Quality issue</option><option value="AVAILABILITY">Availability</option><option value="COMMUNICATION">Communication</option><option value="REQUIREMENT_CHANGED">Requirement changed</option><option value="EXPERT_UNAVAILABLE">Expert unavailable</option><option value="OTHER">Other</option></select></label><label>Comments<textarea [(ngModel)]="comments" maxlength="2000" rows="6" placeholder="Please explain why you need a replacement."></textarea></label></div><button class="primary" (click)="submit()" [disabled]="saving||!comments.trim()">{{saving?'Submitting…':'Submit replacement request'}}</button></section>
<section class="panel"><h2>Replacement history</h2>@if(!history.length){<div class="state">No replacement requests for this engagement.</div>}@else{@for(r of history;track r.id){<article class="history"><div><b>#{{r.id}} · {{r.status}}</b><small>{{r.reasonCode}} · {{r.requestedAt|date:'medium'}}</small><p>{{r.comments}}</p></div>@if(r.newExpertName){<div class="result"><span>New expert</span><b>{{r.newExpertName}}</b><small>Engagement #{{r.newEngagementId}}</small></div>}</article>}}</section></main>`,styles:[`.page{min-height:100vh;background:#f7f9fc;color:#172033;font-family:Inter,system-ui,sans-serif;padding:0 32px 50px}.topbar,.hero,.panel{max-width:980px;margin:auto}.topbar{padding:22px 0;border-bottom:1px solid #e3e8f0;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:850}.subtitle,small{color:#667085;font-size:13px}.subtitle{margin-top:4px}.top-actions{display:flex;gap:8px}.topbar button,.primary{border:1px solid #d5dbe6;background:#fff;color:#172033;border-radius:9px;padding:10px 14px;font-weight:750;cursor:pointer}.hero{padding:48px 0 24px}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:850;color:#315ea8}.hero h1{font-size:40px;margin:8px 0}.hero p{color:#667085;line-height:1.55}.panel{background:#fff;border:1px solid #e1e6ef;border-radius:15px;box-shadow:0 12px 32px rgba(23,32,51,.05);padding:22px;margin-bottom:18px}.panel h2{margin-top:0}.form{display:grid;gap:16px;margin-bottom:18px}label{font-size:12px;font-weight:800;color:#475467}select,textarea{display:block;width:100%;box-sizing:border-box;margin-top:7px;border:1px solid #d5dbe6;border-radius:9px;padding:11px;background:#fff;font:inherit;color:#172033}.primary{background:#172033;color:#fff}.error{max-width:980px;margin:0 auto 18px;padding:12px 14px;border:1px solid #e8b4b4;background:#fff5f5;border-radius:10px;color:#a33}.state{text-align:center;padding:30px;color:#667085}.history{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #edf0f5;padding:16px 0}.history:first-of-type{border-top:0}.history small{display:block;margin-top:5px}.history p{font-size:13px;line-height:1.5}.result{min-width:180px;background:#f7f9fc;padding:12px;border-radius:10px}.result span{display:block;color:#667085;font-size:11px;text-transform:uppercase}.result b{display:block;margin-top:5px}@media(max-width:700px){.page{padding:0 18px 40px}.history{flex-direction:column}.result{min-width:0}.hero h1{font-size:32px}}`]
})
export class CustomerExpertReplacementComponent {private readonly route=inject(ActivatedRoute);private readonly auth=inject(AuthService);private readonly service=inject(ExpertReplacementService);private readonly router=inject(Router);engagementId=Number(this.route.snapshot.paramMap.get('engagementId'));history:ExpertReplacement[]=[];reason='SKILLS_MISMATCH';comments='';saving=false;error='';constructor(){const u=this.auth.getCurrentUser();if(!u||!['CUSTOMER','ROLE_CUSTOMER'].includes(u.role)){this.router.navigateByUrl('/');return;}this.load();}load(){this.service.byEngagement(this.engagementId).subscribe({next:r=>this.history=r??[],error:e=>this.error=e?.error?.message||'Unable to load replacement history.'});}submit(){this.saving=true;this.error='';this.service.request(this.engagementId,this.reason,this.comments.trim()).subscribe({next:()=>{this.saving=false;this.comments='';this.load();},error:e=>{this.saving=false;this.error=e?.error?.message||'Unable to submit replacement request.'}});}back(){this.router.navigateByUrl('/customer/dashboard');}logout(){this.auth.logout();this.router.navigateByUrl('/login');}}
