import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { WorkLogService, WorkLog, EngagementUsage } from '../core/work-log/work-log.service';

@Component({selector:'app-expert-work-logs',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<main class="page"><header class="topbar"><div><b>NeshTek Expert Connect</b><div class="sub">Expert work tracking</div></div><a routerLink="/expert/dashboard">Expert dashboard</a></header>
<section class="content"><div class="eyebrow">Time & work tracking</div><h1>Engagement work log</h1><p class="intro">Record time worked on this active engagement and submit completed entries for customer approval.</p>
@if(error){<div class="state error">{{error}}</div>}
@if(usage){<section class="usage"><div><span>Contract hours</span><b>{{usage.estimatedHours ?? '—'}} hrs</b></div><div><span>Logged</span><b>{{usage.loggedHours}} hrs</b></div><div><span>Remaining</span><b>{{usage.remainingHours ?? '—'}} hrs</b></div><div><span>Utilization</span><b>{{usage.utilizationPercentage ?? '—'}}{{usage.utilizationPercentage !== null ? '%' : ''}}</b></div><div><span>Rate</span><b>{{usage.proposedRate ?? '—'}} {{usage.currencyCode ?? ''}}/hr</b></div><div><span>Approved value</span><b>{{usage.approvedAmount ?? '—'}} {{usage.currencyCode ?? ''}}</b></div></section>
@if(usage.remainingHours !== null && usage.remainingHours <= 0){<div class="warning">The engagement has reached its approved hour limit. New work logs are blocked.</div>} @else if(usage.utilizationPercentage !== null && usage.utilizationPercentage >= 80){<div class="warning">{{usage.remainingHours}} hrs remaining. The engagement is at {{usage.utilizationPercentage}}% utilization.</div>}}
<section class="card form"><h2>Log work</h2><div class="fields"><label>Work date<input type="date" [(ngModel)]="workDate"></label><label>Hours<input type="number" min="0.01" max="24" step="0.25" [(ngModel)]="hours"></label></div><label>Description<textarea rows="4" maxlength="2000" [(ngModel)]="description" placeholder="Describe the work completed..."></textarea></label><button class="primary" [disabled]="saving || (usage?.remainingHours !== null && usage?.remainingHours <= 0)" (click)="create()">{{saving?'Saving…':'Save draft'}}</button></section>
<section class="list"><div class="section-head"><h2>Work entries</h2><button (click)="load()">Refresh</button></div>@if(!logs.length && !loading){<div class="state">No work entries yet.</div>} @for(log of logs;track log.id){<article class="card"><div class="head"><div><b>{{log.workDate}}</b><div class="muted">{{log.hours}} hours</div></div><span class="badge" [class.submitted]="log.status==='SUBMITTED'" [class.approved]="log.status==='APPROVED'" [class.rejected]="log.status==='REJECTED'">{{log.status}}</span></div><p>{{log.description}}</p>@if(log.reviewerComment){<div class="review">{{log.reviewerComment}}</div>}@if(log.status==='DRAFT'||log.status==='REJECTED'){<button class="primary" (click)="submit(log)">Submit for approval</button>}</article>}</section>
</section></main>`,styles:[`.page{min-height:100vh;background:#f7f9fc;color:#172033;font-family:Inter,system-ui,sans-serif;padding:0 32px 56px}.topbar,.content{max-width:1180px;margin:auto}.topbar{padding:22px 0;border-bottom:1px solid #e3e8f0;display:flex;justify-content:space-between;align-items:center}.sub,.muted,.intro{color:#667085;font-size:14px}.sub{margin-top:4px}.topbar a{border:1px solid #d5dbe6;background:#fff;border-radius:9px;padding:10px 14px;text-decoration:none;color:#315ea8;font-weight:750}.content{padding-top:48px}.eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:11px;font-weight:850;color:#315ea8}.content h1{font-size:42px;margin:9px 0}.intro{line-height:1.6}.card,.state{background:#fff;border:1px solid #e1e6ef;border-radius:16px;padding:22px;box-shadow:0 12px 32px rgba(23,32,51,.05)}.usage{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:28px}.usage div{background:#fff;border:1px solid #e1e6ef;border-radius:12px;padding:16px}.usage span{display:block;color:#98a2b3;font-size:11px;text-transform:uppercase;margin-bottom:6px}.usage b{font-size:18px}.warning{margin-top:14px;padding:14px 16px;background:#fff7e6;border:1px solid #f0d59c;border-radius:10px;color:#8a5a00}.form{margin-top:28px}.form h2,.list h2{margin-top:0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}label{display:block;font-size:13px;font-weight:750;margin-bottom:14px}input,textarea{display:block;width:100%;box-sizing:border-box;margin-top:7px;border:1px solid #d5dbe6;border-radius:9px;padding:10px;font:inherit}.primary,.section-head button{border:0;border-radius:9px;padding:10px 15px;font-weight:800;cursor:pointer}.primary{background:#172033;color:#fff}.primary:disabled{opacity:.5}.list{margin-top:36px}.section-head{display:flex;justify-content:space-between;align-items:center}.section-head button{background:#fff;border:1px solid #d5dbe6}.list{display:grid;gap:14px}.head{display:flex;justify-content:space-between;gap:16px}.badge{padding:6px 10px;border-radius:999px;background:#eef2f7;font-size:12px;font-weight:850;height:max-content}.badge.submitted{background:#fff4d6;color:#8a5a00}.badge.approved{background:#ecfdf3;color:#067647}.badge.rejected{background:#fff5f4;color:#b42318}.review{background:#f8fafc;border-radius:9px;padding:10px;margin:14px 0;color:#536078;font-size:13px}.error{color:#b42318;background:#fff5f4;margin-top:20px}@media(max-width:700px){.page{padding:0 18px 40px}.fields,.usage{grid-template-columns:1fr}.content h1{font-size:34px}}`]})
export class ExpertWorkLogsComponent{
 private readonly route=inject(ActivatedRoute); private readonly service=inject(WorkLogService); engagementId=0; logs:WorkLog[]=[]; usage:EngagementUsage|null=null; loading=false;saving=false;error='';workDate=new Date().toISOString().slice(0,10);hours=1;description='';
 constructor(){this.engagementId=Number(this.route.snapshot.paramMap.get('engagementId'));this.load();}
 load(){this.loading=true;this.error='';this.service.listForEngagement(this.engagementId).subscribe({next:p=>{this.logs=p.content??[];this.loading=false},error:e=>{this.error=e?.error?.error||'Unable to load work logs.';this.loading=false}});this.service.getUsage(this.engagementId).subscribe({next:u=>this.usage=u,error:e=>this.error=e?.error?.error||'Unable to load engagement usage.'})}
 create(){if(!this.workDate||!this.hours||!this.description.trim()){this.error='Work date, hours and description are required.';return}this.saving=true;this.error='';this.service.create(this.engagementId,{workDate:this.workDate,hours:Number(this.hours),description:this.description.trim()}).subscribe({next:()=>{this.description='';this.hours=1;this.saving=false;this.load()},error:e=>{this.saving=false;this.error=e?.error?.error||'Unable to save work log.'}})}
 submit(log:WorkLog){this.service.submit(log.id).subscribe({next:u=>{this.logs=this.logs.map(x=>x.id===u.id?u:x);this.load()},error:e=>this.error=e?.error?.error||'Unable to submit work log.'})}
}
