import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { AuthService } from '../core/auth/auth.service';
import { Engagement, ExpertProfile, ExpertService } from '../core/expert/expert.service';
import { EngagementBillingSummary, WorkLogService } from '../core/work-log/work-log.service';

@Component({selector:'app-expert-settlement',standalone:true,imports:[CommonModule,RouterLink],template:`
<main class="page"><header class="topbar"><div><b>NeshTek Expert Connect</b><div class="sub">Expert earnings & settlement</div></div><a routerLink="/expert/dashboard">Expert dashboard</a></header>
<section class="content"><div class="eyebrow">Billing & settlement</div><h1>Earnings & settlement</h1><p class="intro">Track approved earnings across your engagements. Only customer-approved work is included in the payable amount.</p>
@if(error){<div class="state error">{{error}}</div>}
@if(loading){<div class="state">Loading your settlement summary…</div>}
@if(!loading && expert){
<section class="summary"><article><span>Approved earnings</span><b>{{totalApproved | number:'1.0-2'}} {{currency}}</b><small>Customer-approved work</small></article><article><span>Pending approval</span><b>{{totalPending | number:'1.0-2'}} {{currency}}</b><small>Submitted but not approved</small></article><article><span>Rejected value</span><b>{{totalRejected | number:'1.0-2'}} {{currency}}</b><small>Excluded from earnings</small></article><article><span>Approved hours</span><b>{{totalApprovedHours | number:'1.0-2'}} hrs</b><small>Across all engagements</small></article></section>
<section class="card"><div class="section-head"><div><div class="eyebrow">Settlement status</div><h2>Current earnings position</h2></div><button (click)="load()">Refresh</button></div><div class="position"><div><span>Pending settlement</span><b>{{totalApproved | number:'1.0-2'}} {{currency}}</b><small>Eligible based on approved work logs</small></div><div><span>Not yet payable</span><b>{{totalPending | number:'1.0-2'}} {{currency}}</b><small>Requires customer approval</small></div></div><div class="note">Settlement is a billing status only at this stage. No payment is initiated automatically.</div></section>
<section class="engagements"><div class="eyebrow">Engagements</div><h2>Engagement earnings</h2>@if(!rows.length){<div class="state">No engagement billing records found.</div>}@else{@for(row of rows;track row.summary.engagementId){<article class="card row"><div class="main"><h3>{{row.engagement.requirementTitle}}</h3><div class="muted">Customer #{{row.engagement.customerId}} · Engagement #{{row.engagement.id}}</div><div class="meta"><span>{{row.summary.approvedHours}} approved hrs</span><span>{{row.summary.pendingHours}} pending hrs</span><span>{{row.summary.rejectedHours}} rejected hrs</span><span>{{row.summary.hourlyRate ?? row.engagement.agreedRate ?? '—'}} {{row.summary.currencyCode ?? row.engagement.currencyCode ?? ''}}/hr</span></div></div><div class="amount"><span>Approved earnings</span><b>{{row.summary.approvedBilling ?? 0 | number:'1.0-2'}} {{row.summary.currencyCode ?? ''}}</b><a [routerLink]="['/expert/work-logs',row.engagement.id]">View work logs →</a></div></article>}}</section>}
</section></main>`,styles:[`.page{min-height:100vh;background:#f7f9fc;color:#172033;font-family:Inter,system-ui,sans-serif;padding:0 32px 56px;box-sizing:border-box}.topbar,.content{max-width:1180px;margin:auto}.topbar{padding:22px 0;border-bottom:1px solid #e3e8f0;display:flex;justify-content:space-between;align-items:center}.sub,.muted,.intro{color:#667085;font-size:14px}.sub{margin-top:4px}.topbar a{border:1px solid #d5dbe6;background:#fff;border-radius:9px;padding:10px 14px;text-decoration:none;color:#315ea8;font-weight:750}.content{padding-top:46px}.eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:11px;font-weight:850;color:#315ea8}.content h1{font-size:42px;margin:9px 0}.intro{line-height:1.6;max-width:800px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:28px}.summary article,.card,.state{background:#fff;border:1px solid #e1e6ef;border-radius:16px;padding:22px;box-shadow:0 12px 32px rgba(23,32,51,.05)}.summary span,.position span,.amount span{display:block;color:#98a2b3;text-transform:uppercase;font-size:11px;margin-bottom:7px}.summary b{font-size:24px}.summary small,.position small{display:block;color:#667085;margin-top:6px}.card{margin-top:22px}.section-head{display:flex;justify-content:space-between;align-items:flex-start}.section-head h2,.engagements h2{margin:5px 0 0}.section-head button{border:1px solid #d5dbe6;background:#fff;border-radius:9px;padding:9px 14px;font-weight:750}.position{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.position>div{background:#f8fafc;border:1px solid #edf1f6;border-radius:10px;padding:16px}.position b{font-size:22px}.note{margin-top:14px;padding:12px 14px;background:#f8fafc;border-radius:9px;color:#667085;font-size:13px}.engagements{margin-top:38px}.row{display:flex;justify-content:space-between;gap:24px;align-items:center}.main{flex:1}.row h3{margin:0 0 5px;font-size:19px}.meta{display:flex;gap:14px;flex-wrap:wrap;margin-top:14px;color:#536078;font-size:13px;font-weight:700}.amount{text-align:right;min-width:190px}.amount b{display:block;font-size:20px;margin-bottom:9px}.amount a{color:#315ea8;font-size:12px;font-weight:800;text-decoration:none}.error{color:#b42318;background:#fff5f4}.state{color:#667085;margin-top:22px}@media(max-width:900px){.summary{grid-template-columns:repeat(2,1fr)}.row{flex-direction:column;align-items:flex-start}.amount{text-align:left}.position{grid-template-columns:1fr}}@media(max-width:600px){.page{padding:0 18px 40px}.summary{grid-template-columns:1fr}.content h1{font-size:34px}}`]
})
export class ExpertSettlementComponent {
 private readonly auth=inject(AuthService); private readonly expertService=inject(ExpertService); private readonly workLogService=inject(WorkLogService);
 expert:ExpertProfile|null=null; rows:{engagement:Engagement;summary:EngagementBillingSummary}[]=[]; loading=true; error=''; totalApproved=0; totalPending=0; totalRejected=0; totalApprovedHours=0; currency='INR';
 constructor(){this.load()}
 load(){const user=this.auth.getCurrentUser();if(!user){this.error='Please sign in as an expert.';this.loading=false;return}this.loading=true;this.error='';this.expertService.findByEmail(user.email).subscribe({next:expert=>{this.expert=expert;this.expertService.getEngagements(expert.expertId).subscribe({next:page=>{const engagements=page.content??[];if(!engagements.length){this.rows=[];this.finish();return}forkJoin(engagements.map(engagement=>this.workLogService.getBillingSummary(engagement.id))).subscribe({next:summaries=>{this.rows=engagements.map((engagement,i)=>({engagement,summary:summaries[i]}));this.totalApproved=this.rows.reduce((s,r)=>s+(r.summary.approvedBilling??0),0);this.totalPending=this.rows.reduce((s,r)=>s+(r.summary.pendingBilling??0),0);this.totalRejected=this.rows.reduce((s,r)=>s+(r.summary.rejectedValue??0),0);this.totalApprovedHours=this.rows.reduce((s,r)=>s+r.summary.approvedHours,0);this.currency=this.rows.find(r=>r.summary.currencyCode)?.summary.currencyCode??this.rows.find(r=>r.engagement.currencyCode)?.engagement.currencyCode??'INR';this.finish()},error:e=>{this.error=e?.error?.error||'Unable to load billing summaries.';this.finish()}})},error:e=>{this.error=e?.error?.error||'Unable to load engagements.';this.finish()}})},error:e=>{this.error=e?.error?.error||e?.message||'Unable to load your expert profile.';this.finish()}})}
 private finish(){this.loading=false}
}
