ALTER TABLE SETTLEMENT DROP CONSTRAINT CK_SETTLEMENT_STATUS;

ALTER TABLE SETTLEMENT ADD (
    CUSTOMER_APPROVED_AT TIMESTAMP,
    CUSTOMER_REJECTED_AT TIMESTAMP,
    CUSTOMER_COMMENT VARCHAR2(1000 CHAR)
);

ALTER TABLE SETTLEMENT ADD CONSTRAINT CK_SETTLEMENT_STATUS
    CHECK (STATUS IN ('REQUESTED','CUSTOMER_APPROVED','APPROVED_FOR_PAYOUT','PAID','REJECTED'));

CREATE INDEX IX_SETTLEMENT_CUSTOMER_APPROVAL ON SETTLEMENT(CUSTOMER_APPROVED_AT);
