-- Extend the engagement lifecycle to support PAUSED status.
-- V12 created CK_ENGAGEMENT_STATUS with only READY, ACTIVE, COMPLETED and CANCELLED.
ALTER TABLE ENGAGEMENT DROP CONSTRAINT CK_ENGAGEMENT_STATUS;

ALTER TABLE ENGAGEMENT ADD CONSTRAINT CK_ENGAGEMENT_STATUS
    CHECK (STATUS IN ('READY','ACTIVE','PAUSED','COMPLETED','CANCELLED'));
