CREATE TABLE expert (
    expert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(320) NOT NULL,
    mobile_number VARCHAR2(30) NOT NULL,
    date_of_birth DATE NOT NULL,
    country VARCHAR2(100),
    city VARCHAR2(100),
    timezone VARCHAR2(100),
    linkedin_url VARCHAR2(500),
    total_experience_years NUMBER(4,1),
    status VARCHAR2(30) DEFAULT 'SUBMITTED' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uk_expert_email UNIQUE (email),
    CONSTRAINT uk_expert_mobile UNIQUE (mobile_number),
    CONSTRAINT ck_expert_status CHECK (status IN ('SUBMITTED','UNDER_REVIEW','VERIFICATION','APPROVED','REJECTED','SUSPENDED'))
);

CREATE TABLE expert_skill (
    expert_skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expert_id NUMBER NOT NULL,
    skill_order NUMBER(2) NOT NULL,
    skill_name VARCHAR2(150) NOT NULL,
    skill_level VARCHAR2(30),
    years_experience NUMBER(4,1),
    CONSTRAINT fk_skill_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE,
    CONSTRAINT ck_skill_order CHECK (skill_order BETWEEN 1 AND 10),
    CONSTRAINT uk_expert_skill_order UNIQUE (expert_id, skill_order)
);

CREATE TABLE expert_expertise (
    expert_id NUMBER PRIMARY KEY,
    technical_expertise CLOB NOT NULL,
    word_count NUMBER(8) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_expertise_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE,
    CONSTRAINT ck_expertise_word_count CHECK (word_count >= 1000)
);

CREATE TABLE expert_availability (
    expert_id NUMBER PRIMARY KEY,
    hours_per_week NUMBER(5,1),
    available_from DATE,
    timezone VARCHAR2(100),
    weekday_available CHAR(1) DEFAULT 'Y',
    weekend_available CHAR(1) DEFAULT 'N',
    CONSTRAINT fk_availability_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE,
    CONSTRAINT ck_weekday_available CHECK (weekday_available IN ('Y','N')),
    CONSTRAINT ck_weekend_available CHECK (weekend_available IN ('Y','N'))
);

CREATE TABLE expert_consulting (
    expert_id NUMBER PRIMARY KEY,
    minimum_engagement_hours NUMBER(5,1),
    maximum_engagement_hours NUMBER(5,1),
    hourly_rate NUMBER(12,2),
    currency_code VARCHAR2(10),
    CONSTRAINT fk_consulting_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id),
    CONSTRAINT ck_consulting_hours CHECK (minimum_engagement_hours IS NULL OR maximum_engagement_hours IS NULL OR minimum_engagement_hours <= maximum_engagement_hours)
);

CREATE TABLE expert_certification (
    certification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expert_id NUMBER NOT NULL,
    certification_name VARCHAR2(250) NOT NULL,
    issuing_organization VARCHAR2(250),
    certification_number VARCHAR2(150),
    issue_date DATE,
    expiry_date DATE,
    CONSTRAINT fk_certification_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE
);

CREATE TABLE expert_document (
    document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expert_id NUMBER NOT NULL,
    document_type VARCHAR2(50) NOT NULL,
    object_storage_key VARCHAR2(1000) NOT NULL,
    original_file_name VARCHAR2(500),
    content_type VARCHAR2(150),
    verification_status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_document_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE,
    CONSTRAINT ck_document_status CHECK (verification_status IN ('PENDING','VERIFIED','REJECTED'))
);

CREATE TABLE expert_verification (
    expert_id NUMBER PRIMARY KEY,
    mobile_verified CHAR(1) DEFAULT 'N' NOT NULL,
    email_verified CHAR(1) DEFAULT 'N' NOT NULL,
    linkedin_verified CHAR(1) DEFAULT 'N' NOT NULL,
    identity_verified CHAR(1) DEFAULT 'N' NOT NULL,
    experience_verified CHAR(1) DEFAULT 'N' NOT NULL,
    verified_at TIMESTAMP,
    verified_by VARCHAR2(150),
    CONSTRAINT fk_verification_expert FOREIGN KEY (expert_id) REFERENCES expert(expert_id) ON DELETE CASCADE,
    CONSTRAINT ck_mobile_verified CHECK (mobile_verified IN ('Y','N')),
    CONSTRAINT ck_email_verified CHECK (email_verified IN ('Y','N')),
    CONSTRAINT ck_linkedin_verified CHECK (linkedin_verified IN ('Y','N')),
    CONSTRAINT ck_identity_verified CHECK (identity_verified IN ('Y','N')),
    CONSTRAINT ck_experience_verified CHECK (experience_verified IN ('Y','N'))
);

CREATE INDEX ix_expert_status ON expert(status);
CREATE INDEX ix_expert_city ON expert(city);
CREATE INDEX ix_expert_skill_name ON expert_skill(skill_name);
CREATE INDEX ix_expert_document_status ON expert_document(verification_status);
