ALTER TABLE REPLACEMENT_FINANCIAL_RECONCILIATION ADD (
    RESOLUTION_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING_REVIEW' NOT NULL,
    RESOLUTION_ACTION VARCHAR2(30 CHAR),
    RESOLUTION_AMOUNT NUMBER(14,2),
    RESOLUTION_NOTE VARCHAR2(2000 CHAR),
    RESOLVED_AT TIMESTAMP,
    RESOLVED_BY_USER_ID NUMBER,
    CONSTRAINT FK_RECON_RESOLVED_BY FOREIGN KEY (RESOLVED_BY_USER_ID) REFERENCES APP_USER(USER_ID),
    CONSTRAINT CK_RECON_RES_STATUS CHECK (RESOLUTION_STATUS IN ('PENDING_REVIEW','RESOLVED')),
    CONSTRAINT CK_RECON_RES_ACTION CHECK (RESOLUTION_ACTION IS NULL OR RESOLUTION_ACTION IN ('NO_ADJUSTMENT','REFUND_CUSTOMER','CUSTOMER_CREDIT','BALANCE_DUE','MANUAL_REVIEW'))
);

CREATE INDEX IX_RECON_RES_STATUS ON REPLACEMENT_FINANCIAL_RECONCILIATION(RESOLUTION_STATUS);
