ALTER TABLE ENGAGEMENT ADD (
    REPLACEMENT_OF_ENGAGEMENT_ID NUMBER,
    REPLACED_BY_ENGAGEMENT_ID NUMBER
);

ALTER TABLE ENGAGEMENT ADD CONSTRAINT FK_ENG_REPLACEMENT_OF
    FOREIGN KEY (REPLACEMENT_OF_ENGAGEMENT_ID) REFERENCES ENGAGEMENT(ENGAGEMENT_ID);

ALTER TABLE ENGAGEMENT ADD CONSTRAINT FK_ENG_REPLACED_BY
    FOREIGN KEY (REPLACED_BY_ENGAGEMENT_ID) REFERENCES ENGAGEMENT(ENGAGEMENT_ID);

CREATE INDEX IX_ENG_REPLACEMENT_OF ON ENGAGEMENT(REPLACEMENT_OF_ENGAGEMENT_ID);
CREATE INDEX IX_ENG_REPLACED_BY ON ENGAGEMENT(REPLACED_BY_ENGAGEMENT_ID);

ALTER TABLE EXPERT_REPLACEMENT_REQUEST ADD (
    NEW_EXPERT_ID NUMBER,
    NEW_ENGAGEMENT_ID NUMBER
);

ALTER TABLE EXPERT_REPLACEMENT_REQUEST ADD CONSTRAINT FK_REPL_REQ_NEW_EXPERT
    FOREIGN KEY (NEW_EXPERT_ID) REFERENCES EXPERT(EXPERT_ID);

ALTER TABLE EXPERT_REPLACEMENT_REQUEST ADD CONSTRAINT FK_REPL_REQ_NEW_ENG
    FOREIGN KEY (NEW_ENGAGEMENT_ID) REFERENCES ENGAGEMENT(ENGAGEMENT_ID);

CREATE INDEX IX_REPL_REQ_NEW_EXPERT ON EXPERT_REPLACEMENT_REQUEST(NEW_EXPERT_ID);
CREATE INDEX IX_REPL_REQ_NEW_ENG ON EXPERT_REPLACEMENT_REQUEST(NEW_ENGAGEMENT_ID);

ALTER TABLE EXPERT_REPLACEMENT_REQUEST DROP CONSTRAINT CK_REPL_REQ_STATUS;
ALTER TABLE EXPERT_REPLACEMENT_REQUEST ADD CONSTRAINT CK_REPL_REQ_STATUS
    CHECK (STATUS IN ('REQUESTED','APPROVED','REPLACED','REJECTED','CANCELLED'));
