ALTER TABLE INVOICE ADD (
    PDF_CONTENT BLOB,
    PDF_FILE_NAME VARCHAR2(255 CHAR),
    PDF_CONTENT_TYPE VARCHAR2(100 CHAR) DEFAULT 'application/pdf',
    PDF_GENERATED_AT TIMESTAMP
);

CREATE INDEX IX_INVOICE_PDF_GENERATED ON INVOICE(PDF_GENERATED_AT);
