ALTER TABLE expert DROP CONSTRAINT ck_expert_status;

ALTER TABLE expert ADD CONSTRAINT ck_expert_status
CHECK (status IN ('SUBMITTED','UNDER_REVIEW','VERIFICATION','APPROVED','ACTIVE','REJECTED','SUSPENDED'));
