ALTER TABLE CUSTOMER_REQUIREMENT_SKILL
    ADD MANDATORY CHAR(1) DEFAULT 'Y' NOT NULL;

ALTER TABLE CUSTOMER_REQUIREMENT_SKILL
    ADD CONSTRAINT CK_REQ_SKILL_MANDATORY CHECK (MANDATORY IN ('Y','N'));
