ALTER TABLE CUSTOMER_REQUIREMENT ADD CUSTOMER_ID NUMBER;

ALTER TABLE CUSTOMER_REQUIREMENT ADD CONSTRAINT FK_REQUIREMENT_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

CREATE INDEX IX_REQUIREMENT_CUSTOMER ON CUSTOMER_REQUIREMENT(CUSTOMER_ID);
